apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-blue
  namespace: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
      version: blue
  template:
    metadata:
      labels:
        app: hello
        version: blue
    spec:
      containers:
      - name: hello
        image: vipindevops/blue-green:tagname:1.0
        ports:
        - containerPort: 80
