apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-green
  namespace: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
      version: green
  template:
    metadata:
      labels:
        app: hello
        version: green
    spec:
      containers:
      - name: hello
        image: vipindevops/blue-green:tagname:1.1
        ports:
        - containerPort: 80
