kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-green
  namespace: hello
spec:
  replicas: 0
  selector:
    matchLabels:
      app: hello
      version: green
  template:
    metadata:
      labels:
        app: hello
        version: green
    spec:
      containers:
      - name: hello
        image: chudinov/nginx-hello:1.1
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 100Mi
            cpu: 200m
          requests:
            memory: 50Mi
            cpu: 100m
            
