apiVersion: v1
kind: Service
metadata:
  name: hello-svc-stable
  namespace: hello
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: hello
    version: blue
  type: LoadBalancer